### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by francois2metz**
Add the github actions that I use on my own plugins:

- the basic ci 
- the release workflow to build and push steampipe plugin to github package

### CODE REVIEW

**Comment by judell** [comment]
Thanks for these updates Francois! While we're at it, can we explain here a bit more about what this does? I'm not yet familiar with the release workflow. What will happen if I push the `Approve and run` button here, for example?

**Comment by francois2metz** [comment]
Hi Jon,

On each push (or pull request), it will first compile the plugin and then run [golangci-lint](https://golangci-lint.run/).

When you push a tag, it will publish the steampipe plugin to github package to <username>/<plugin-name>.

**Comment by judell** [comment]
OK, it's running. I can see that it builds the plugin. I'll try pushing a tag to see what happens there.

**Comment by judell** [comment]
Looks like both things happen.

image

**Comment by judell** [comment]
OK, it's published. Very cool! Trying:

```
$ steampipe plugin install ghcr.io/judell/steampipe-plugin-hello

ghcr.io/judell/st... [====================================================================] Done


Skipped the following plugin:

Plugin:   steampipe-plugin-hello@latest
Reason:   failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

Should I expect my $GITHUB_TOKEN to suffice here?

**Comment by judell** [comment]
So, the hub release process pushes to the Google container registry, and this is a DIY alternative that pushes to the GitHub container registry?

The benefit, if I understand correctly, being that people can make their own plugins installable with `steampipe plugin install`? 

Very cool!!!

**Comment by francois2metz** [comment]
Exactly. It's a great way to use the plugin as the hub publishing process can take some times. It also nice for private plugins.

**Comment by judell** [comment]
What about the `github plugin install` auth?

**Pull request merged**
